apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-deploy
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry-pod
          image: hahaha12353/service-registry
          ports:
            - containerPort: 8761